### ISSUE TITLE
Key url in Config/mongo.json

### ISSUE THREAD

**Issue by sunapollo** [vapor/mongo-provider#17] opened 2017-06-15 04:02 UTC
mongo.json

``` json
{
  "user": "root",
  "password": "",
  "database": "dwblog",
  "port": "27017",
  "host": "127.0.0.1"
}
```
then run
error

> fatal error: Error raised at top level: Configuration error: Key url in Config/mongo.json of type String required.: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-802.0.53/src/swift/stdlib/public/core/ErrorType.swift, line 188

**Comment by ntokozo-online** [comment] 2017-06-16 18:08
I'm also experiencing this.

**Comment by api-live** [comment] 2017-07-03 20:59
I believe the issue is that the provider is looking for the credentials to be passed in as a URL for some reason. For example, it should look something like: 

`
{
    "url": "mongodb://<db-user>:<db-password>@<host>:<port>/<database>"
}
`

**Comment by jkmathew** [comment] 2017-07-06 11:48
Hi @api-live I have added url key to mongo.json config file, 


now my mongo.json is

```
{
    "user": "dbadmin",
    "password": "adminThink",
    "database": "mySitedb",
    "port": "27017",
    "host": "127.0.0.1",
    "url": "mongodb://dbadmin:adminThink@127.0.0.1:27017/mySitedb"
}
```

but getting error like 
> fatal error: Error raised at top level: MongoKitten.MongoError.invalidResponse([{"ok":0.0,"errmsg":"not authorized on mySitedb to execute command { find: \"fluent\", batchSize: 100, filter: {}, sort: { batch: -1 }, skip: 0, limit: 1 }","code":13,"codeName":"Unauthorized"}]): file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-802.0.53/src/swift/stdlib/public/core/ErrorType.swift, line 188
> 2017-07-06 17:12:21.528303 Run[49120:174764] fatal error: Error raised at top level: MongoKitten.MongoError.invalidResponse([{"ok":0.0,"errmsg":"not authorized on mySitedb to execute command { find: \"fluent\", batchSize: 100, filter: {}, sort: { batch: -1 }, skip: 0, limit: 1 }","code":13,"codeName":"Unauthorized"}]): file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-802.0.53/src/swift/stdlib/public/core/ErrorType.swift, line 188

I am able to use mongo shell with following code
`$ mongo --port 27017 -u "dbadmin" -p "adminThink" --authenticationDatabase "admin"`

**Comment by vzsg** [comment] 2017-07-07 06:11
Closing this too, as the README now shows the expected format: an URL instead of separated parameters.

**Closed as completed by vzsg** 2017-07-07 06:11 UTC
